version: "3.8"
services:
    nodeserver:
        build:
            context: ./apps/api
        ports:
            - "3001:3001"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        environment:
            - DB_USER=username
            - DB_PASSWORD=password
            - DB_NAME=databasename
            - DB_HOST=host.docker.internal
            - JWT_SECRET=jwtsecret
    nginx:
        restart: always
        build:
            context: ./apps/ui
        ports:
            - "80:80"
