version: "3.8"
services:
    nodeserver:
        build:
            context: ./apps/api
        ports:
            - "3001:3001"
        extra_hosts:
            - "host.docker.internal:host-gateway"
        env_file:
            - .env
    nginx:
        restart: always
        build:
            context: ./apps/ui
        ports:
            - "80:80"
