version: "3.8"
services:
    nodeserver:
        restart: always
        build:
            context: ./apps/api
        extra_hosts:
            - "host.docker.internal:host-gateway"
        networks:
            - dt
        volumes:
            - database:/data
        env_file: "apps/api/.env"
    nginx:
        restart: always
        build:
            context: ./apps/ui
        networks:
            - dt
    router:
        restart: always
        build:
            context: ./apps/router/nginxrouter
        networks:
            - dt
        ports:
            - "80:80"
networks:
    dt:
        name: dt
volumes:
    database:
